name: CI

on:
  workflow_dispatch:
  push: 
    branches: 
    - master
   
jobs: 
  Dotnet_Task:
    runs-on: ubuntu-latest
    steps:
    - name: Remove Previous Dotnet Version
      run : |
        cd /usr/share/dotnet/
        rm -rf *
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.1.426
    - name: Listing Dotnet version
      run: dotnet --version

    - name: Listing files
      run: ls 
     
    - name: Dotnet build
      run: docker build -t githubcisharni.azurecr.io/demoenv:${{ github.run_id }} .
      
